# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dc3f7b6686d304378522abb6cc672b2c34dcf749c247ad8d99790c27955898dd2aecc54f052821a29d00085ea9d177923d7f4df1a068797107c03aaeb1b84ca
  weather:
    host: 'http://api.openweathermap.org'
    api_key: cbaef12f904a0a06fcf42ffd5ea30fbf

test:
  secret_key_base: 5bc0b969cec99548950fcbaa834db9dae4b991b119125d1953659389973852db647285f12c631d4ca5b26eb439b97ccc0e33dc63fafcf9967a336f4cb2694010
  weather:
    host: 'http://api.openweathermap.org'

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  weather:
    host: 'http://api.openweathermap.org'
